version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs"]
	skip_doc_coverage = ["class-expression", "method-definition"]

[[transformers]]
name = "prettier"